# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = ""
  publish = "dist"
  command = '''
    sed -i "s|PLACES_API_KEY|$PLACES_API_KEY|g" netlify.toml && \
    npm run generate'''

# Skip Optional Dependencies
# Turn Off Logging
# https://dev.to/lukeocodes/make-nuxt-js-go-brrrrrrrr-30-minute-to-1-minute-builds-on-netlify-f6e
[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--no-optional"
  CI = "1"

[[redirects]]
  from = "/api/places*"
  to = "https://maps.googleapis.com/maps/api/place/details/json?fields=rating,reviews,user_ratings_total&placeid=ChIJs4LylmzXAhURyiITK_fxbhE&key=PLACES_API_KEY:splat"
  status = 200

[[redirects]]
  from = "/en*"
  to = "/:splat"
[[redirects]]
  from = "/order"
  to = "https://www.tabitorder.com/?siteName=sushinbagel#/start"
[[redirects]]
  from = "/about"
  to = "/story"
[[redirects]]
  from = "/he/about"
  to = "/he/story"

[[redirects]]
  from = "/products*"
  to = "/menu"
[[redirects]]
  from = "/en/products*"
  to = "/menu"
[[redirects]]
  from = "/he/products*"
  to = "/he/menu"
[[redirects]]
  from = "/collections*"
  to = "/menu"
[[redirects]]
  from = "/en/collections*"
  to = "/menu"
[[redirects]]
  from = "/he/collections*"
  to = "/he/menu"

[[redirects]]
  from = "/admin$"
  to = "/admin/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
